compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 16
  offload_optimizer_device: none
  offload_param_device: none
  zero_stage: 3
  zero3_init_flag: true
  zero3_save_16bit_model: true
distributed_type: DEEPSPEED # MULTI_GPU #
mixed_precision: bf16
downcast_bf16: yes
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false